development:
  secret_key_base: aa43d7e86f1f862fc6de9a7d063dc6cb
  secret_api_key: 70de9a0100a37603d6d2fa24c2ec5427
  secret_mail: jeanmi.delatuile@gmail.com
test:
  secret_key_base: aa43d7e86f1f862fc6de9a7d063dc6cb
  secret_api_key: 70de9a0100a37603d6d2fa24c2ec5427
  secret_mail: jeanmi.delatuile@gmail.com
production:
  secret_key_base: aa43d7e86f1f862fc6de9a7d063dc6cb
  secret_api_key: 70de9a0100a37603d6d2fa24c2ec5427
  secret_mail: jeanmi.delatuile@gmail.com