development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>
  secret_api_key: <%= ENV["SECRET_KEY_API_DEV"] %>
  secret_mail: <%= ENV["SECRET_KEY_MAIL"] %>
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>
  secret_api_key: <%= ENV["SECRET_KEY_API_DEV"] %>
  secret_mail: <%= ENV["SECRET_KEY_MAIL"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>
  secret_api_key: <%= ENV["SECRET_KEY_API_DEV"] %>
  secret_mail: <%= ENV["SECRET_KEY_MAIL"] %>